//! Operation type definitions for the MAGI graph engine.
//!
//! All graph operation types. This is the sole source of truth for operation
//! identifiers — the PDK does not define operations (plugins don't need them).


// OperationType

/// Enumerates all visual programming operations.
///
/// Each variant corresponds to a node operation in the graph editor.
/// Operations are organized by category: arithmetic, comparison, logic,
/// bitwise, control flow, string, type conversion, array, map, and bytes.
///
/// All graph operation types. This is the sole source of truth for operation
/// identifiers — the PDK does not define operations (plugins don't need them).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OperationType {
    // Arithmetic (14)
    Add,
    Subtract,
    Multiply,
    Divide,
    Modulo,
    Power,
    Sqrt,
    Cbrt,
    Hypot,
    Negate,
    Abs,
    Min,
    Max,
    Round,
    Floor,
    Ceil,

    // Comparison (6)
    Equal,
    NotEqual,
    Greater,
    Less,
    GreaterEq,
    LessEq,

    // Logic (4)
    And,
    Or,
    Not,
    Xor,

    // Bitwise (6)
    BitAnd,
    BitOr,
    BitXor,
    BitNot,
    BitShiftLeft,
    BitShiftRight,

    // Control Flow (5)
    IfElse,
    Switch,
    Coalesce,
    TryCatch,
    Error,

    // V2 Language Constructs (5)
    FunctionDef,
    FunctionCall,
    AsyncSpawn,
    AsyncAwait,
    LoopGroup,

    // String (20)
    Concat,
    Split,
    Substring,
    Length,
    Replace,
    ToUpper,
    ToLower,
    Trim,
    TrimStart,
    TrimEnd,
    Contains,
    StartsWith,
    EndsWith,
    CharAt,
    IndexOf,
    PadStart,
    PadEnd,
    RegexMatch,
    StringJoin,
    StringTemplate,

    // Type Conversion (10)
    ToString,
    ToInt64,
    ToFloat64,
    ToBool,
    ToBytes,
    FromBytes,
    ParseJson,
    ToJson,
    CharFromCode,
    CharCode,

    // Array (17)
    ArrayGet,
    ArraySet,
    ArrayPush,
    ArrayPop,
    ArrayShift,
    ArrayInsert,
    ArrayRemove,
    ArrayLength,
    ArraySlice,
    ArrayConcat,
    ArrayContains,
    ArrayReverse,
    ArrayFlatten,
    ArraySort,
    ArrayJoin,
    ArrayFilterNulls,
    ArrayFromMap,

    // Map (10)
    MapGet,
    MapSet,
    MapDelete,
    MapHas,
    MapKeys,
    MapValues,
    MapEntries,
    MapMerge,
    MapFromEntries,
    MapSize,

    // Bytes (17)
    BytesLength,
    BytesSlice,
    BytesConcat,
    BytesContains,
    Base64Encode,
    Base64Decode,
    BytesCompare,
    BytesEqual,
    BytesHasPrefix,
    BytesHasSuffix,
    BytesIndex,
    BytesJoin,
    BytesRepeat,
    BytesSplit,
    BytesTrim,
    BytesFromString,
    BytesToString,

    // Errors (5)
    ErrorNew,
    ErrorWrap,
    ErrorUnwrap,
    ErrorIs,
    ErrorChain,

    // Iteration (2)
    Range,
    Reduce,

    // JSON (6)
    JsonGet,
    JsonSet,
    JsonDelete,
    JsonFlatten,
    JsonMerge,
    JsonType,
    // JSON Extended (4)
    JsonValidate,
    JsonPrettyPrint,
    JsonCompact,
    JsonQuery,

    // DateTime (6)
    NowTimestamp,
    FormatTimestamp,
    ParseTimestamp,
    TimestampAdd,
    TimestampDiff,
    Sleep,

    // Hash/Encode (8)
    HashSha256,
    HashSha1,
    HashBlake3,
    HashMd5,
    UrlEncode,
    UrlDecode,
    HexEncode,
    HexDecode,

    // String extended (8)
    StringReverse,
    StringRepeat,
    StringLines,
    StringWords,
    RegexReplace,
    RegexExtract,
    StringCount,
    StringFormat,

    // Control Flow extended (2)
    Assert,
    DebugLog,

    // Type Conversion extended (2)
    Typeof,
    Default,

    // Array Higher-Order (20)
    ArrayMap,
    ArrayFilter,
    ArrayFlatMap,
    ArrayFind,
    ArrayFindIndex,
    ArrayEvery,
    ArraySome,
    ArrayZip,
    ArrayEnumerate,
    ArrayScan,
    ArrayTake,
    ArraySkip,
    ArrayTakeWhile,
    ArraySkipWhile,
    ArrayGroupBy,
    ArraySortBy,
    ArrayUnique,
    ArrayChunk,
    ArrayWindow,
    ArrayPartition,

    // Map Higher-Order (3)
    MapMapValues,
    MapFilterEntries,
    MapUpdate,

    // String (1)
    StringChars,

    // Math Aggregate (6)
    MathSum,
    MathProduct,
    MathAverage,
    MathMinOf,
    MathMaxOf,
    MathCount,

    // Type Checking (7)
    IsNull,
    IsString,
    IsNumber,
    IsArray,
    IsMap,
    IsBool,
    IsBytes,

    // Math Extended (27)
    Sin,
    Cos,
    Tan,
    Asin,
    Acos,
    Atan,
    Atan2,
    Sinh,
    Cosh,
    Tanh,
    Log,
    Ln,
    Log2,
    Log10,
    Exp,
    ToRadians,
    ToDegrees,
    Clamp,
    Lerp,
    Sign,
    Gcd,
    Lcm,
    IsNan,
    IsInfinite,
    IsFinite,
    ApproxEq,
    Remap,

    // Random (10)
    RandomInt,
    RandomFloat,
    RandomBool,
    RandomBytes,
    RandomRange,
    RandomChoice,
    RandomShuffle,
    RandomSample,
    RandomUuid,
    RandomString,

    // Filesystem (15)
    FsRead,
    FsWrite,
    FsAppend,
    FsExists,
    FsRemove,
    FsList,
    FsMkdir,
    FsCopy,
    FsMove,
    FsSize,
    FsIsFile,
    FsIsDir,
    FsChmod,
    FsSymlink,
    FsReadlink,

    // Environment (7)
    EnvGet,
    EnvHas,
    EnvKeys,
    OsName,
    OsArch,
    ProcessPid,
    CurrentDir,

    // Network (10)
    HttpGet,
    HttpPost,
    HttpPut,
    HttpDelete,
    HttpRequest,
    HttpHead,
    HttpOptions,
    HttpPatch,
    UrlParse,
    UrlJoin,

    // TCP (7)
    TcpConnect,
    TcpWrite,
    TcpRead,
    TcpClose,
    TcpBind,
    TcpAccept,
    TcpServerClose,

    // UDP (4)
    UdpBind,
    UdpSendTo,
    UdpRecvFrom,
    UdpClose,

    // WebSocket (4)
    WsConnect,
    WsSend,
    WsReceive,
    WsClose,

    // SSE (3)
    SseConnect,
    SseReadEvent,
    SseClose,

    // HTTP Server (4)
    HttpServerStart,
    HttpServerReceive,
    HttpServerRespond,
    HttpServerStop,

    // Certificate (6)
    CertGenerate,
    CertParse,
    CertInfo,
    CertVerify,
    KeyGenerate,
    CertSelfSigned,

    // Path (10)
    PathJoin,
    PathBasename,
    PathDirname,
    PathExtension,
    PathStem,
    PathIsAbsolute,
    PathNormalize,
    PathSplit,
    PathWithExtension,
    PathParent,

    // YAML (2+4)
    YamlParse,
    YamlStringify,
    YamlValidate,
    YamlToJson,
    YamlFromJson,
    YamlMerge,

    // XML (2)
    XmlParse,
    XmlStringify,

    // CSV (4)
    CsvParse,
    CsvStringify,
    CsvHeaders,
    CsvParseRows,

    // TOML (2)
    TomlParse,
    TomlStringify,

    // Regex (5)
    RegexSplit,
    RegexEscape,
    RegexTest,
    RegexCaptures,
    RegexFindAll,

    // UUID (4)
    UuidV4,
    UuidParse,
    UuidIsValid,
    UuidNil,

    // Crypto Extended (4)
    HashSha512,
    HmacSha256,
    HashCrc32,
    ConstantTimeEq,

    // Compress (6)
    CompressZstd,
    DecompressZstd,
    CompressLz4,
    DecompressLz4,
    CompressGzip,
    DecompressGzip,

    // Format (6)
    FmtNumber,
    FmtBytes,
    FmtDuration,
    FmtHex,
    FmtBinary,
    FmtPercent,

    // Convert Extended (2)
    ParseInt,
    ParseFloat,

    // Time Extended (8)
    Duration,
    Elapsed,
    TimeSleep,
    AddDuration,
    SubDuration,
    TimeDiff,
    StartOf,
    EndOf,

    // Stats (12)
    StatsMean,
    StatsMedian,
    StatsMode,
    StatsVariance,
    StatsStdDev,
    StatsMinBy,
    StatsMaxBy,
    StatsSum,
    StatsPercentile,
    StatsQuantile,
    StatsCovariance,
    StatsCorrelation,

    // Text (10)
    TextWrap,
    TextDedent,
    TextIndent,
    TextPadLeft,
    TextPadRight,
    TextTruncate,
    TextSlug,
    TextCamelCase,
    TextSnakeCase,
    TextTitleCase,

    // Encode (4 new — base64/hex already exist)
    HtmlEscape,
    HtmlUnescape,
    Base32Encode,
    Base32Decode,

    // Reflect (8)
    ReflectTypeOf,
    ReflectTypeName,
    ReflectIsType,
    ReflectFields,
    ReflectHasField,
    ReflectCallable,
    ReflectArity,
    ReflectInspect,

    // Collections (8)
    SetFrom,
    SetUnion,
    SetIntersection,
    SetDifference,
    SetSymmetricDifference,
    Counter,
    MostCommon,
    OrderedMap,

    // Sort (8)
    SortAsc,
    SortDesc,
    SortBy,
    SortByKey,
    StableSort,
    IsSorted,
    BinarySearch,
    SortReverse,

    // Subprocess (3)
    Exec,
    ExecStatus,
    ExecOutput,

    // Sync (6)
    MutexNew,
    MutexLock,
    MutexUnlock,
    WaitgroupNew,
    WaitgroupDone,
    WaitgroupWait,

    // Concurrency (1)
    AwaitAll,

    // Log (4)
    LogInfo,
    LogWarn,
    LogError,
    LogDebug,

    // Itertools (5)
    IterChain,
    IterCycle,
    IterRepeat,
    IterProduct,
    IterPairwise,

    // Template (1)
    TemplateRender,

    // Flag (2)
    FlagParse,
    FlagArgs,

    // Additional math (7)
    MathGamma,
    MathLgamma,
    MathErf,
    MathErfc,
    MathExpm1,
    MathNextafter,
    MathSignbit,

    // Additional OS (3)
    FsChown,
    FsHardlink,
    OsPipe,

    // Additional strconv (2)
    FormatFloat,
    ParseUint,

    // Additional CLI (3)
    CliFix,
    CliClean,
    CliTree,

    // Platform — Terminal (4)
    RawModeEnable,
    RawModeDisable,
    ReadByte,
    ReadByteTimeout,

    // Platform — SDL2 Graphics (11)
    SdlInit,
    SdlSetColor,
    SdlClear,
    SdlPresent,
    SdlDrawPixel,
    SdlDrawLine,
    SdlFillRect,
    SdlPollEvent,
    SdlDelay,
    SdlTicks,
    SdlDestroy,

    // Platform — Audio (4)
    AudioStreamNew,
    AudioWriteSamples,
    AudioDrain,
    AudioClose,

    // Platform — WebGPU (12)
    GpuInit,
    GpuCreateBuffer,
    GpuCreateShader,
    GpuCreatePipeline,
    GpuBeginRenderPass,
    GpuDraw,
    GpuEndRenderPass,
    GpuSubmit,
    GpuPresent,
    GpuWriteBuffer,
    GpuCreateTexture,
    GpuDestroy,
}

impl OperationType {
    /// Return the string identifier used in serialization and the UI.
    pub fn as_str(&self) -> &'static str {
        match self {
            OperationType::Add => "add",
            OperationType::Subtract => "subtract",
            OperationType::Multiply => "multiply",
            OperationType::Divide => "divide",
            OperationType::Modulo => "modulo",
            OperationType::Power => "power",
            OperationType::Sqrt => "sqrt",
            OperationType::Cbrt => "cbrt",
            OperationType::Hypot => "hypot",
            OperationType::Negate => "negate",
            OperationType::Abs => "abs",
            OperationType::Min => "min",
            OperationType::Max => "max",
            OperationType::Round => "round",
            OperationType::Floor => "floor",
            OperationType::Ceil => "ceil",
            OperationType::Equal => "equal",
            OperationType::NotEqual => "not_equal",
            OperationType::Greater => "greater",
            OperationType::Less => "less",
            OperationType::GreaterEq => "greater_eq",
            OperationType::LessEq => "less_eq",
            OperationType::And => "and",
            OperationType::Or => "or",
            OperationType::Not => "not",
            OperationType::Xor => "xor",
            OperationType::BitAnd => "bit_and",
            OperationType::BitOr => "bit_or",
            OperationType::BitXor => "bit_xor",
            OperationType::BitNot => "bit_not",
            OperationType::BitShiftLeft => "bit_shift_left",
            OperationType::BitShiftRight => "bit_shift_right",
            OperationType::IfElse => "if_else",
            OperationType::Switch => "switch",
            OperationType::Coalesce => "coalesce",
            OperationType::TryCatch => "try_catch",
            OperationType::Error => "error",
            OperationType::FunctionDef => "function_def",
            OperationType::FunctionCall => "function_call",
            OperationType::AsyncSpawn => "async_spawn",
            OperationType::AsyncAwait => "async_await",
            OperationType::LoopGroup => "loop_group",
            OperationType::Concat => "concat",
            OperationType::Split => "split",
            OperationType::Substring => "substring",
            OperationType::Length => "length",
            OperationType::Replace => "replace",
            OperationType::ToUpper => "to_upper",
            OperationType::ToLower => "to_lower",
            OperationType::Trim => "trim",
            OperationType::TrimStart => "trim_start",
            OperationType::TrimEnd => "trim_end",
            OperationType::Contains => "contains",
            OperationType::StartsWith => "starts_with",
            OperationType::EndsWith => "ends_with",
            OperationType::CharAt => "char_at",
            OperationType::IndexOf => "index_of",
            OperationType::PadStart => "pad_start",
            OperationType::PadEnd => "pad_end",
            OperationType::RegexMatch => "regex_match",
            OperationType::StringJoin => "string_join",
            OperationType::StringTemplate => "string_template",
            OperationType::ToString => "to_string",
            OperationType::ToInt64 => "to_int64",
            OperationType::ToFloat64 => "to_float64",
            OperationType::ToBool => "to_bool",
            OperationType::ToBytes => "to_bytes",
            OperationType::FromBytes => "from_bytes",
            OperationType::ParseJson => "parse_json",
            OperationType::ToJson => "to_json",
            OperationType::CharFromCode => "char_from_code",
            OperationType::CharCode => "char_code",
            OperationType::ArrayGet => "array_get",
            OperationType::ArraySet => "array_set",
            OperationType::ArrayPush => "array_push",
            OperationType::ArrayPop => "array_pop",
            OperationType::ArrayShift => "array_shift",
            OperationType::ArrayInsert => "array_insert",
            OperationType::ArrayRemove => "array_remove",
            OperationType::ArrayLength => "array_length",
            OperationType::ArraySlice => "array_slice",
            OperationType::ArrayConcat => "array_concat",
            OperationType::ArrayContains => "array_contains",
            OperationType::ArrayReverse => "array_reverse",
            OperationType::ArrayFlatten => "array_flatten",
            OperationType::ArraySort => "array_sort",
            OperationType::ArrayJoin => "array_join",
            OperationType::ArrayFilterNulls => "array_filter_nulls",
            OperationType::ArrayFromMap => "array_from_map",
            OperationType::MapGet => "map_get",
            OperationType::MapSet => "map_set",
            OperationType::MapDelete => "map_delete",
            OperationType::MapHas => "map_has",
            OperationType::MapKeys => "map_keys",
            OperationType::MapValues => "map_values",
            OperationType::MapEntries => "map_entries",
            OperationType::MapMerge => "map_merge",
            OperationType::MapFromEntries => "map_from_entries",
            OperationType::MapSize => "map_size",
            OperationType::BytesLength => "bytes_length",
            OperationType::BytesSlice => "bytes_slice",
            OperationType::BytesConcat => "bytes_concat",
            OperationType::BytesContains => "bytes_contains",
            OperationType::Base64Encode => "base64_encode",
            OperationType::Base64Decode => "base64_decode",
            OperationType::BytesCompare => "bytes_compare",
            OperationType::BytesEqual => "bytes_equal",
            OperationType::BytesHasPrefix => "bytes_has_prefix",
            OperationType::BytesHasSuffix => "bytes_has_suffix",
            OperationType::BytesIndex => "bytes_index",
            OperationType::BytesJoin => "bytes_join",
            OperationType::BytesRepeat => "bytes_repeat",
            OperationType::BytesSplit => "bytes_split",
            OperationType::BytesTrim => "bytes_trim",
            OperationType::BytesFromString => "bytes_from_string",
            OperationType::BytesToString => "bytes_to_string",
            OperationType::ErrorNew => "error_new",
            OperationType::ErrorWrap => "error_wrap",
            OperationType::ErrorUnwrap => "error_unwrap",
            OperationType::ErrorIs => "error_is",
            OperationType::ErrorChain => "error_chain",
            OperationType::Range => "range",
            OperationType::Reduce => "reduce",
            // JSON
            OperationType::JsonGet => "json_get",
            OperationType::JsonSet => "json_set",
            OperationType::JsonDelete => "json_delete",
            OperationType::JsonFlatten => "json_flatten",
            OperationType::JsonMerge => "json_merge",
            OperationType::JsonType => "json_type",
            OperationType::JsonValidate => "json_validate",
            OperationType::JsonPrettyPrint => "json_pretty_print",
            OperationType::JsonCompact => "json_compact",
            OperationType::JsonQuery => "json_query",
            // DateTime
            OperationType::NowTimestamp => "now_timestamp",
            OperationType::FormatTimestamp => "format_timestamp",
            OperationType::ParseTimestamp => "parse_timestamp",
            OperationType::TimestampAdd => "timestamp_add",
            OperationType::TimestampDiff => "timestamp_diff",
            OperationType::Sleep => "sleep",
            // Hash/Encode
            OperationType::HashSha256 => "hash_sha256",
            OperationType::HashSha1 => "hash_sha1",
            OperationType::HashBlake3 => "hash_blake3",
            OperationType::HashMd5 => "hash_md5",
            OperationType::UrlEncode => "url_encode",
            OperationType::UrlDecode => "url_decode",
            OperationType::HexEncode => "hex_encode",
            OperationType::HexDecode => "hex_decode",
            OperationType::StringReverse => "string_reverse",
            OperationType::StringRepeat => "string_repeat",
            OperationType::StringLines => "string_lines",
            OperationType::StringWords => "string_words",
            OperationType::RegexReplace => "regex_replace",
            OperationType::RegexExtract => "regex_extract",
            OperationType::StringCount => "string_count",
            OperationType::StringFormat => "string_format",
            OperationType::Assert => "assert",
            OperationType::DebugLog => "debug_log",
            OperationType::Typeof => "typeof",
            OperationType::Default => "default",
            // Array Higher-Order
            OperationType::ArrayMap => "array_map",
            OperationType::ArrayFilter => "array_filter",
            OperationType::ArrayFlatMap => "array_flat_map",
            OperationType::ArrayFind => "array_find",
            OperationType::ArrayFindIndex => "array_find_index",
            OperationType::ArrayEvery => "array_every",
            OperationType::ArraySome => "array_some",
            OperationType::ArrayZip => "array_zip",
            OperationType::ArrayEnumerate => "array_enumerate",
            OperationType::ArrayScan => "array_scan",
            OperationType::ArrayTake => "array_take",
            OperationType::ArraySkip => "array_skip",
            OperationType::ArrayTakeWhile => "array_take_while",
            OperationType::ArraySkipWhile => "array_skip_while",
            OperationType::ArrayGroupBy => "array_group_by",
            OperationType::ArraySortBy => "array_sort_by",
            OperationType::ArrayUnique => "array_unique",
            OperationType::ArrayChunk => "array_chunk",
            OperationType::ArrayWindow => "array_window",
            OperationType::ArrayPartition => "array_partition",
            // Map Higher-Order
            OperationType::MapMapValues => "map_map_values",
            OperationType::MapFilterEntries => "map_filter_entries",
            OperationType::MapUpdate => "map_update",
            OperationType::StringChars => "string_chars",
            // Math Aggregate
            OperationType::MathSum => "math_sum",
            OperationType::MathProduct => "math_product",
            OperationType::MathAverage => "math_average",
            OperationType::MathMinOf => "math_min_of",
            OperationType::MathMaxOf => "math_max_of",
            OperationType::MathCount => "math_count",
            // Type Checking
            OperationType::IsNull => "is_null",
            OperationType::IsString => "is_string",
            OperationType::IsNumber => "is_number",
            OperationType::IsArray => "is_array",
            OperationType::IsMap => "is_map",
            OperationType::IsBool => "is_bool",
            OperationType::IsBytes => "is_bytes",
            // Math Extended
            OperationType::Sin => "sin",
            OperationType::Cos => "cos",
            OperationType::Tan => "tan",
            OperationType::Asin => "asin",
            OperationType::Acos => "acos",
            OperationType::Atan => "atan",
            OperationType::Atan2 => "atan2",
            OperationType::Sinh => "sinh",
            OperationType::Cosh => "cosh",
            OperationType::Tanh => "tanh",
            OperationType::Log => "log",
            OperationType::Ln => "ln",
            OperationType::Log2 => "log2",
            OperationType::Log10 => "log10",
            OperationType::Exp => "exp",
            OperationType::ToRadians => "to_radians",
            OperationType::ToDegrees => "to_degrees",
            OperationType::Clamp => "clamp",
            OperationType::Lerp => "lerp",
            OperationType::Sign => "sign",
            OperationType::Gcd => "gcd",
            OperationType::Lcm => "lcm",
            OperationType::IsNan => "is_nan",
            OperationType::IsInfinite => "is_infinite",
            OperationType::IsFinite => "is_finite",
            OperationType::ApproxEq => "approx_eq",
            OperationType::Remap => "remap",
            OperationType::RandomInt => "random_int",
            OperationType::RandomFloat => "random_float",
            OperationType::RandomBool => "random_bool",
            OperationType::RandomBytes => "random_bytes",
            OperationType::RandomRange => "random_range",
            OperationType::RandomChoice => "random_choice",
            OperationType::RandomShuffle => "random_shuffle",
            OperationType::RandomSample => "random_sample",
            OperationType::RandomUuid => "random_uuid",
            OperationType::RandomString => "random_string",
            OperationType::FsRead => "fs_read",
            OperationType::FsWrite => "fs_write",
            OperationType::FsAppend => "fs_append",
            OperationType::FsExists => "fs_exists",
            OperationType::FsRemove => "fs_remove",
            OperationType::FsList => "fs_list",
            OperationType::FsMkdir => "fs_mkdir",
            OperationType::FsCopy => "fs_copy",
            OperationType::FsMove => "fs_move",
            OperationType::FsSize => "fs_size",
            OperationType::FsIsFile => "fs_is_file",
            OperationType::FsIsDir => "fs_is_dir",
            OperationType::FsChmod => "fs_chmod",
            OperationType::FsSymlink => "fs_symlink",
            OperationType::FsReadlink => "fs_readlink",
            OperationType::EnvGet => "env_get",
            OperationType::EnvHas => "env_has",
            OperationType::EnvKeys => "env_keys",
            OperationType::OsName => "os_name",
            OperationType::OsArch => "os_arch",
            OperationType::ProcessPid => "process_pid",
            OperationType::CurrentDir => "current_dir",
            OperationType::HttpGet => "http_get",
            OperationType::HttpPost => "http_post",
            OperationType::HttpPut => "http_put",
            OperationType::HttpDelete => "http_delete",
            OperationType::HttpRequest => "http_request",
            OperationType::HttpHead => "http_head",
            OperationType::HttpOptions => "http_options",
            OperationType::HttpPatch => "http_patch",
            OperationType::UrlParse => "url_parse",
            OperationType::UrlJoin => "url_join",
            // TCP
            OperationType::TcpConnect => "tcp_connect",
            OperationType::TcpWrite => "tcp_write",
            OperationType::TcpRead => "tcp_read",
            OperationType::TcpClose => "tcp_close",
            OperationType::TcpBind => "tcp_bind",
            OperationType::TcpAccept => "tcp_accept",
            OperationType::TcpServerClose => "tcp_server_close",
            // UDP
            OperationType::UdpBind => "udp_bind",
            OperationType::UdpSendTo => "udp_send_to",
            OperationType::UdpRecvFrom => "udp_recv_from",
            OperationType::UdpClose => "udp_close",
            // WebSocket
            OperationType::WsConnect => "ws_connect",
            OperationType::WsSend => "ws_send",
            OperationType::WsReceive => "ws_receive",
            OperationType::WsClose => "ws_close",
            // SSE
            OperationType::SseConnect => "sse_connect",
            OperationType::SseReadEvent => "sse_read_event",
            OperationType::SseClose => "sse_close",
            // HTTP Server
            OperationType::HttpServerStart => "http_server_start",
            OperationType::HttpServerReceive => "http_server_receive",
            OperationType::HttpServerRespond => "http_server_respond",
            OperationType::HttpServerStop => "http_server_stop",
            OperationType::CertGenerate => "cert_generate",
            OperationType::CertParse => "cert_parse",
            OperationType::CertInfo => "cert_info",
            OperationType::CertVerify => "cert_verify",
            OperationType::KeyGenerate => "key_generate",
            OperationType::CertSelfSigned => "cert_self_signed",
            OperationType::PathJoin => "path_join",
            OperationType::PathBasename => "path_basename",
            OperationType::PathDirname => "path_dirname",
            OperationType::PathExtension => "path_extension",
            OperationType::PathStem => "path_stem",
            OperationType::PathIsAbsolute => "path_is_absolute",
            OperationType::PathNormalize => "path_normalize",
            OperationType::PathSplit => "path_split",
            OperationType::PathWithExtension => "path_with_extension",
            OperationType::PathParent => "path_parent",
            // YAML
            OperationType::YamlParse => "yaml_parse",
            OperationType::YamlStringify => "yaml_stringify",
            OperationType::YamlValidate => "yaml_validate",
            OperationType::YamlToJson => "yaml_to_json",
            OperationType::YamlFromJson => "yaml_from_json",
            OperationType::YamlMerge => "yaml_merge",
            OperationType::XmlParse => "xml_parse",
            OperationType::XmlStringify => "xml_stringify",
            // CSV
            OperationType::CsvParse => "csv_parse",
            OperationType::CsvStringify => "csv_stringify",
            OperationType::CsvHeaders => "csv_headers",
            OperationType::CsvParseRows => "csv_parse_rows",
            // TOML
            OperationType::TomlParse => "toml_parse",
            OperationType::TomlStringify => "toml_stringify",
            // Regex Extended
            OperationType::RegexSplit => "regex_split",
            OperationType::RegexEscape => "regex_escape",
            OperationType::RegexTest => "regex_test",
            OperationType::RegexCaptures => "regex_captures",
            OperationType::RegexFindAll => "regex_find_all",
            // UUID
            OperationType::UuidV4 => "uuid_v4",
            OperationType::UuidParse => "uuid_parse",
            OperationType::UuidIsValid => "uuid_is_valid",
            OperationType::UuidNil => "uuid_nil",
            // Crypto Extended
            OperationType::HashSha512 => "hash_sha512",
            OperationType::HmacSha256 => "hmac_sha256",
            OperationType::HashCrc32 => "hash_crc32",
            OperationType::ConstantTimeEq => "constant_time_eq",
            OperationType::CompressZstd => "compress_zstd",
            OperationType::DecompressZstd => "decompress_zstd",
            OperationType::CompressLz4 => "compress_lz4",
            OperationType::DecompressLz4 => "decompress_lz4",
            OperationType::CompressGzip => "compress_gzip",
            OperationType::DecompressGzip => "decompress_gzip",
            OperationType::FmtNumber => "fmt_number",
            OperationType::FmtBytes => "fmt_bytes",
            OperationType::FmtDuration => "fmt_duration",
            OperationType::FmtHex => "fmt_hex",
            OperationType::FmtBinary => "fmt_binary",
            OperationType::FmtPercent => "fmt_percent",
            // Convert Extended
            OperationType::ParseInt => "parse_int",
            OperationType::ParseFloat => "parse_float",
            // Time Extended
            OperationType::Duration => "duration",
            OperationType::Elapsed => "elapsed",
            OperationType::TimeSleep => "time_sleep",
            OperationType::AddDuration => "add_duration",
            OperationType::SubDuration => "sub_duration",
            OperationType::TimeDiff => "time_diff",
            OperationType::StartOf => "start_of",
            OperationType::EndOf => "end_of",
            OperationType::StatsMean => "stats_mean",
            OperationType::StatsMedian => "stats_median",
            OperationType::StatsMode => "stats_mode",
            OperationType::StatsVariance => "stats_variance",
            OperationType::StatsStdDev => "stats_std_dev",
            OperationType::StatsMinBy => "stats_min_by",
            OperationType::StatsMaxBy => "stats_max_by",
            OperationType::StatsSum => "stats_sum",
            OperationType::StatsPercentile => "stats_percentile",
            OperationType::StatsQuantile => "stats_quantile",
            OperationType::StatsCovariance => "stats_covariance",
            OperationType::StatsCorrelation => "stats_correlation",
            OperationType::TextWrap => "text_wrap",
            OperationType::TextDedent => "text_dedent",
            OperationType::TextIndent => "text_indent",
            OperationType::TextPadLeft => "text_pad_left",
            OperationType::TextPadRight => "text_pad_right",
            OperationType::TextTruncate => "text_truncate",
            OperationType::TextSlug => "text_slug",
            OperationType::TextCamelCase => "text_camel_case",
            OperationType::TextSnakeCase => "text_snake_case",
            OperationType::TextTitleCase => "text_title_case",
            // Encode Extended
            OperationType::HtmlEscape => "html_escape",
            OperationType::HtmlUnescape => "html_unescape",
            OperationType::Base32Encode => "base32_encode",
            OperationType::Base32Decode => "base32_decode",
            OperationType::ReflectTypeOf => "reflect_type_of",
            OperationType::ReflectTypeName => "reflect_type_name",
            OperationType::ReflectIsType => "reflect_is_type",
            OperationType::ReflectFields => "reflect_fields",
            OperationType::ReflectHasField => "reflect_has_field",
            OperationType::ReflectCallable => "reflect_callable",
            OperationType::ReflectArity => "reflect_arity",
            OperationType::ReflectInspect => "reflect_inspect",
            OperationType::SetFrom => "set_from",
            OperationType::SetUnion => "set_union",
            OperationType::SetIntersection => "set_intersection",
            OperationType::SetDifference => "set_difference",
            OperationType::SetSymmetricDifference => "set_symmetric_difference",
            OperationType::Counter => "counter",
            OperationType::MostCommon => "most_common",
            OperationType::OrderedMap => "ordered_map",
            OperationType::SortAsc => "sort_asc",
            OperationType::SortDesc => "sort_desc",
            OperationType::SortBy => "sort_by",
            OperationType::SortByKey => "sort_by_key",
            OperationType::StableSort => "stable_sort",
            OperationType::IsSorted => "is_sorted",
            OperationType::BinarySearch => "binary_search",
            OperationType::SortReverse => "sort_reverse",
            OperationType::Exec => "exec",
            OperationType::ExecStatus => "exec_status",
            OperationType::ExecOutput => "exec_output",
            OperationType::MutexNew => "mutex_new",
            OperationType::MutexLock => "mutex_lock",
            OperationType::MutexUnlock => "mutex_unlock",
            OperationType::WaitgroupNew => "waitgroup_new",
            OperationType::WaitgroupDone => "waitgroup_done",
            OperationType::WaitgroupWait => "waitgroup_wait",
            OperationType::AwaitAll => "await_all",
            OperationType::LogInfo => "log_info",
            OperationType::LogWarn => "log_warn",
            OperationType::LogError => "log_error",
            OperationType::LogDebug => "log_debug",
            OperationType::IterChain => "iter_chain",
            OperationType::IterCycle => "iter_cycle",
            OperationType::IterRepeat => "iter_repeat",
            OperationType::IterProduct => "iter_product",
            OperationType::IterPairwise => "iter_pairwise",
            OperationType::TemplateRender => "template_render",
            OperationType::FlagParse => "flag_parse",
            OperationType::FlagArgs => "flag_args",
            OperationType::MathGamma => "gamma",
            OperationType::MathLgamma => "lgamma",
            OperationType::MathErf => "erf",
            OperationType::MathErfc => "erfc",
            OperationType::MathExpm1 => "expm1",
            OperationType::MathNextafter => "nextafter",
            OperationType::MathSignbit => "signbit",
            OperationType::FsChown => "chown",
            OperationType::FsHardlink => "hardlink",
            OperationType::OsPipe => "pipe",
            OperationType::FormatFloat => "format_float",
            OperationType::ParseUint => "parse_uint",
            OperationType::CliFix => "cli_fix",
            OperationType::CliClean => "cli_clean",
            OperationType::CliTree => "cli_tree",
            // Platform — Terminal
            OperationType::RawModeEnable => "raw_mode_enable",
            OperationType::RawModeDisable => "raw_mode_disable",
            OperationType::ReadByte => "read_byte",
            OperationType::ReadByteTimeout => "read_byte_timeout",
            // Platform — SDL2
            OperationType::SdlInit => "sdl_init",
            OperationType::SdlSetColor => "sdl_set_color",
            OperationType::SdlClear => "sdl_clear",
            OperationType::SdlPresent => "sdl_present",
            OperationType::SdlDrawPixel => "sdl_draw_pixel",
            OperationType::SdlDrawLine => "sdl_draw_line",
            OperationType::SdlFillRect => "sdl_fill_rect",
            OperationType::SdlPollEvent => "sdl_poll_event",
            OperationType::SdlDelay => "sdl_delay",
            OperationType::SdlTicks => "sdl_ticks",
            OperationType::SdlDestroy => "sdl_destroy",
            // Platform — Audio
            OperationType::AudioStreamNew => "audio_stream_new",
            OperationType::AudioWriteSamples => "audio_write_samples",
            OperationType::AudioDrain => "audio_drain",
            OperationType::AudioClose => "audio_close",
            // Platform — WebGPU
            OperationType::GpuInit => "gpu_init",
            OperationType::GpuCreateBuffer => "gpu_create_buffer",
            OperationType::GpuCreateShader => "gpu_create_shader",
            OperationType::GpuCreatePipeline => "gpu_create_pipeline",
            OperationType::GpuBeginRenderPass => "gpu_begin_render_pass",
            OperationType::GpuDraw => "gpu_draw",
            OperationType::GpuEndRenderPass => "gpu_end_render_pass",
            OperationType::GpuSubmit => "gpu_submit",
            OperationType::GpuPresent => "gpu_present",
            OperationType::GpuWriteBuffer => "gpu_write_buffer",
            OperationType::GpuCreateTexture => "gpu_create_texture",
            OperationType::GpuDestroy => "gpu_destroy",
        }
    }

    /// Parse an operation type from its string identifier.
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "add" => Some(OperationType::Add),
            "subtract" => Some(OperationType::Subtract),
            "multiply" => Some(OperationType::Multiply),
            "divide" => Some(OperationType::Divide),
            "modulo" => Some(OperationType::Modulo),
            "power" => Some(OperationType::Power),
            "sqrt" => Some(OperationType::Sqrt),
            "cbrt" => Some(OperationType::Cbrt),
            "hypot" => Some(OperationType::Hypot),
            "negate" => Some(OperationType::Negate),
            "abs" => Some(OperationType::Abs),
            "min" => Some(OperationType::Min),
            "max" => Some(OperationType::Max),
            "round" => Some(OperationType::Round),
            "floor" => Some(OperationType::Floor),
            "ceil" => Some(OperationType::Ceil),
            "equal" => Some(OperationType::Equal),
            "not_equal" => Some(OperationType::NotEqual),
            "greater" => Some(OperationType::Greater),
            "less" => Some(OperationType::Less),
            "greater_eq" => Some(OperationType::GreaterEq),
            "less_eq" => Some(OperationType::LessEq),
            "and" => Some(OperationType::And),
            "or" => Some(OperationType::Or),
            "not" => Some(OperationType::Not),
            "xor" => Some(OperationType::Xor),
            "bit_and" => Some(OperationType::BitAnd),
            "bit_or" => Some(OperationType::BitOr),
            "bit_xor" => Some(OperationType::BitXor),
            "bit_not" => Some(OperationType::BitNot),
            "bit_shift_left" => Some(OperationType::BitShiftLeft),
            "bit_shift_right" => Some(OperationType::BitShiftRight),
            "if_else" => Some(OperationType::IfElse),
            "switch" => Some(OperationType::Switch),
            "coalesce" => Some(OperationType::Coalesce),
            "try_catch" => Some(OperationType::TryCatch),
            "error" => Some(OperationType::Error),
            "function_def" => Some(OperationType::FunctionDef),
            "function_call" => Some(OperationType::FunctionCall),
            "async_spawn" => Some(OperationType::AsyncSpawn),
            "async_await" => Some(OperationType::AsyncAwait),
            "loop_group" => Some(OperationType::LoopGroup),
            "concat" => Some(OperationType::Concat),
            "split" => Some(OperationType::Split),
            "substring" => Some(OperationType::Substring),
            "length" => Some(OperationType::Length),
            "replace" => Some(OperationType::Replace),
            "to_upper" => Some(OperationType::ToUpper),
            "to_lower" => Some(OperationType::ToLower),
            "trim" => Some(OperationType::Trim),
            "trim_start" => Some(OperationType::TrimStart),
            "trim_end" => Some(OperationType::TrimEnd),
            "contains" => Some(OperationType::Contains),
            "starts_with" => Some(OperationType::StartsWith),
            "ends_with" => Some(OperationType::EndsWith),
            "char_at" => Some(OperationType::CharAt),
            "index_of" => Some(OperationType::IndexOf),
            "pad_start" => Some(OperationType::PadStart),
            "pad_end" => Some(OperationType::PadEnd),
            "regex_match" => Some(OperationType::RegexMatch),
            "string_join" => Some(OperationType::StringJoin),
            "string_template" => Some(OperationType::StringTemplate),
            "to_string" => Some(OperationType::ToString),
            "to_int64" => Some(OperationType::ToInt64),
            "to_float64" => Some(OperationType::ToFloat64),
            "to_bool" => Some(OperationType::ToBool),
            "to_bytes" => Some(OperationType::ToBytes),
            "from_bytes" => Some(OperationType::FromBytes),
            "parse_json" => Some(OperationType::ParseJson),
            "to_json" => Some(OperationType::ToJson),
            "char_from_code" => Some(OperationType::CharFromCode),
            "char_code" => Some(OperationType::CharCode),
            "array_get" => Some(OperationType::ArrayGet),
            "array_set" => Some(OperationType::ArraySet),
            "array_push" => Some(OperationType::ArrayPush),
            "array_pop" => Some(OperationType::ArrayPop),
            "array_shift" => Some(OperationType::ArrayShift),
            "array_insert" => Some(OperationType::ArrayInsert),
            "array_remove" => Some(OperationType::ArrayRemove),
            "array_length" => Some(OperationType::ArrayLength),
            "array_slice" => Some(OperationType::ArraySlice),
            "array_concat" => Some(OperationType::ArrayConcat),
            "array_contains" => Some(OperationType::ArrayContains),
            "array_reverse" => Some(OperationType::ArrayReverse),
            "array_flatten" => Some(OperationType::ArrayFlatten),
            "array_sort" => Some(OperationType::ArraySort),
            "array_join" => Some(OperationType::ArrayJoin),
            "array_filter_nulls" => Some(OperationType::ArrayFilterNulls),
            "array_from_map" => Some(OperationType::ArrayFromMap),
            "map_get" => Some(OperationType::MapGet),
            "map_set" => Some(OperationType::MapSet),
            "map_delete" => Some(OperationType::MapDelete),
            "map_has" => Some(OperationType::MapHas),
            "map_keys" => Some(OperationType::MapKeys),
            "map_values" => Some(OperationType::MapValues),
            "map_entries" => Some(OperationType::MapEntries),
            "map_merge" => Some(OperationType::MapMerge),
            "map_from_entries" => Some(OperationType::MapFromEntries),
            "map_size" => Some(OperationType::MapSize),
            "bytes_length" => Some(OperationType::BytesLength),
            "bytes_slice" => Some(OperationType::BytesSlice),
            "bytes_concat" => Some(OperationType::BytesConcat),
            "bytes_contains" => Some(OperationType::BytesContains),
            "base64_encode" => Some(OperationType::Base64Encode),
            "base64_decode" => Some(OperationType::Base64Decode),
            "bytes_compare" => Some(OperationType::BytesCompare),
            "bytes_equal" => Some(OperationType::BytesEqual),
            "bytes_has_prefix" => Some(OperationType::BytesHasPrefix),
            "bytes_has_suffix" => Some(OperationType::BytesHasSuffix),
            "bytes_index" => Some(OperationType::BytesIndex),
            "bytes_join" => Some(OperationType::BytesJoin),
            "bytes_repeat" => Some(OperationType::BytesRepeat),
            "bytes_split" => Some(OperationType::BytesSplit),
            "bytes_trim" => Some(OperationType::BytesTrim),
            "bytes_from_string" => Some(OperationType::BytesFromString),
            "bytes_to_string" => Some(OperationType::BytesToString),
            "error_new" => Some(OperationType::ErrorNew),
            "error_wrap" => Some(OperationType::ErrorWrap),
            "error_unwrap" => Some(OperationType::ErrorUnwrap),
            "error_is" => Some(OperationType::ErrorIs),
            "error_chain" => Some(OperationType::ErrorChain),
            "range" => Some(OperationType::Range),
            "reduce" => Some(OperationType::Reduce),
            // JSON
            "json_get" => Some(OperationType::JsonGet),
            "json_set" => Some(OperationType::JsonSet),
            "json_delete" => Some(OperationType::JsonDelete),
            "json_flatten" => Some(OperationType::JsonFlatten),
            "json_merge" => Some(OperationType::JsonMerge),
            "json_type" => Some(OperationType::JsonType),
            "json_validate" => Some(OperationType::JsonValidate),
            "json_pretty_print" => Some(OperationType::JsonPrettyPrint),
            "json_compact" => Some(OperationType::JsonCompact),
            "json_query" => Some(OperationType::JsonQuery),
            // DateTime
            "now_timestamp" => Some(OperationType::NowTimestamp),
            "format_timestamp" => Some(OperationType::FormatTimestamp),
            "parse_timestamp" => Some(OperationType::ParseTimestamp),
            "timestamp_add" => Some(OperationType::TimestampAdd),
            "timestamp_diff" => Some(OperationType::TimestampDiff),
            "sleep" => Some(OperationType::Sleep),
            // Hash/Encode
            "hash_sha256" => Some(OperationType::HashSha256),
            "hash_sha1" => Some(OperationType::HashSha1),
            "hash_blake3" => Some(OperationType::HashBlake3),
            "hash_md5" => Some(OperationType::HashMd5),
            "url_encode" => Some(OperationType::UrlEncode),
            "url_decode" => Some(OperationType::UrlDecode),
            "hex_encode" => Some(OperationType::HexEncode),
            "hex_decode" => Some(OperationType::HexDecode),
            "string_reverse" => Some(OperationType::StringReverse),
            "string_repeat" => Some(OperationType::StringRepeat),
            "string_lines" => Some(OperationType::StringLines),
            "string_words" => Some(OperationType::StringWords),
            "regex_replace" => Some(OperationType::RegexReplace),
            "regex_extract" => Some(OperationType::RegexExtract),
            "string_count" => Some(OperationType::StringCount),
            "string_format" => Some(OperationType::StringFormat),
            "assert" => Some(OperationType::Assert),
            "debug_log" => Some(OperationType::DebugLog),
            "typeof" => Some(OperationType::Typeof),
            "default" => Some(OperationType::Default),
            // Array Higher-Order
            "array_map" => Some(OperationType::ArrayMap),
            "array_filter" => Some(OperationType::ArrayFilter),
            "array_flat_map" => Some(OperationType::ArrayFlatMap),
            "array_find" => Some(OperationType::ArrayFind),
            "array_find_index" => Some(OperationType::ArrayFindIndex),
            "array_every" => Some(OperationType::ArrayEvery),
            "array_some" => Some(OperationType::ArraySome),
            "array_zip" => Some(OperationType::ArrayZip),
            "array_enumerate" => Some(OperationType::ArrayEnumerate),
            "array_scan" => Some(OperationType::ArrayScan),
            "array_take" => Some(OperationType::ArrayTake),
            "array_skip" => Some(OperationType::ArraySkip),
            "array_take_while" => Some(OperationType::ArrayTakeWhile),
            "array_skip_while" => Some(OperationType::ArraySkipWhile),
            "array_group_by" => Some(OperationType::ArrayGroupBy),
            "array_sort_by" => Some(OperationType::ArraySortBy),
            "array_unique" => Some(OperationType::ArrayUnique),
            "array_chunk" => Some(OperationType::ArrayChunk),
            "array_window" => Some(OperationType::ArrayWindow),
            "array_partition" => Some(OperationType::ArrayPartition),
            // Map Higher-Order
            "map_map_values" => Some(OperationType::MapMapValues),
            "map_filter_entries" => Some(OperationType::MapFilterEntries),
            "map_update" => Some(OperationType::MapUpdate),
            "string_chars" => Some(OperationType::StringChars),
            // Math Aggregate
            "math_sum" => Some(OperationType::MathSum),
            "math_product" => Some(OperationType::MathProduct),
            "math_average" => Some(OperationType::MathAverage),
            "math_min_of" => Some(OperationType::MathMinOf),
            "math_max_of" => Some(OperationType::MathMaxOf),
            "math_count" => Some(OperationType::MathCount),
            // Type Checking
            "is_null" => Some(OperationType::IsNull),
            "is_string" => Some(OperationType::IsString),
            "is_number" => Some(OperationType::IsNumber),
            "is_array" => Some(OperationType::IsArray),
            "is_map" => Some(OperationType::IsMap),
            "is_bool" => Some(OperationType::IsBool),
            "is_bytes" => Some(OperationType::IsBytes),
            // Math Extended
            "sin" => Some(OperationType::Sin),
            "cos" => Some(OperationType::Cos),
            "tan" => Some(OperationType::Tan),
            "asin" => Some(OperationType::Asin),
            "acos" => Some(OperationType::Acos),
            "atan" => Some(OperationType::Atan),
            "atan2" => Some(OperationType::Atan2),
            "sinh" => Some(OperationType::Sinh),
            "cosh" => Some(OperationType::Cosh),
            "tanh" => Some(OperationType::Tanh),
            "log" => Some(OperationType::Log),
            "ln" => Some(OperationType::Ln),
            "log2" => Some(OperationType::Log2),
            "log10" => Some(OperationType::Log10),
            "exp" => Some(OperationType::Exp),
            "to_radians" => Some(OperationType::ToRadians),
            "to_degrees" => Some(OperationType::ToDegrees),
            "clamp" => Some(OperationType::Clamp),
            "lerp" => Some(OperationType::Lerp),
            "sign" => Some(OperationType::Sign),
            "gcd" => Some(OperationType::Gcd),
            "lcm" => Some(OperationType::Lcm),
            "is_nan" => Some(OperationType::IsNan),
            "is_infinite" => Some(OperationType::IsInfinite),
            "is_finite" => Some(OperationType::IsFinite),
            "approx_eq" => Some(OperationType::ApproxEq),
            "remap" => Some(OperationType::Remap),
            "random_int" => Some(OperationType::RandomInt),
            "random_float" => Some(OperationType::RandomFloat),
            "random_bool" => Some(OperationType::RandomBool),
            "random_bytes" => Some(OperationType::RandomBytes),
            "random_range" => Some(OperationType::RandomRange),
            "random_choice" => Some(OperationType::RandomChoice),
            "random_shuffle" => Some(OperationType::RandomShuffle),
            "random_sample" => Some(OperationType::RandomSample),
            "random_uuid" => Some(OperationType::RandomUuid),
            "random_string" => Some(OperationType::RandomString),
            "fs_read" => Some(OperationType::FsRead),
            "fs_write" => Some(OperationType::FsWrite),
            "fs_append" => Some(OperationType::FsAppend),
            "fs_exists" => Some(OperationType::FsExists),
            "fs_remove" => Some(OperationType::FsRemove),
            "fs_list" => Some(OperationType::FsList),
            "fs_mkdir" => Some(OperationType::FsMkdir),
            "fs_copy" => Some(OperationType::FsCopy),
            "fs_move" => Some(OperationType::FsMove),
            "fs_size" => Some(OperationType::FsSize),
            "fs_is_file" => Some(OperationType::FsIsFile),
            "fs_is_dir" => Some(OperationType::FsIsDir),
            "fs_chmod" => Some(OperationType::FsChmod),
            "fs_symlink" => Some(OperationType::FsSymlink),
            "fs_readlink" => Some(OperationType::FsReadlink),
            "env_get" => Some(OperationType::EnvGet),
            "env_has" => Some(OperationType::EnvHas),
            "env_keys" => Some(OperationType::EnvKeys),
            "os_name" => Some(OperationType::OsName),
            "os_arch" => Some(OperationType::OsArch),
            "process_pid" => Some(OperationType::ProcessPid),
            "current_dir" => Some(OperationType::CurrentDir),
            "http_get" => Some(OperationType::HttpGet),
            "http_post" => Some(OperationType::HttpPost),
            "http_put" => Some(OperationType::HttpPut),
            "http_delete" => Some(OperationType::HttpDelete),
            "http_request" => Some(OperationType::HttpRequest),
            "http_head" => Some(OperationType::HttpHead),
            "http_options" => Some(OperationType::HttpOptions),
            "http_patch" => Some(OperationType::HttpPatch),
            "url_parse" => Some(OperationType::UrlParse),
            "url_join" => Some(OperationType::UrlJoin),
            // TCP
            "tcp_connect" => Some(OperationType::TcpConnect),
            "tcp_write" => Some(OperationType::TcpWrite),
            "tcp_read" => Some(OperationType::TcpRead),
            "tcp_close" => Some(OperationType::TcpClose),
            "tcp_bind" => Some(OperationType::TcpBind),
            "tcp_accept" => Some(OperationType::TcpAccept),
            "tcp_server_close" => Some(OperationType::TcpServerClose),
            // UDP
            "udp_bind" => Some(OperationType::UdpBind),
            "udp_send_to" => Some(OperationType::UdpSendTo),
            "udp_recv_from" => Some(OperationType::UdpRecvFrom),
            "udp_close" => Some(OperationType::UdpClose),
            // WebSocket
            "ws_connect" => Some(OperationType::WsConnect),
            "ws_send" => Some(OperationType::WsSend),
            "ws_receive" => Some(OperationType::WsReceive),
            "ws_close" => Some(OperationType::WsClose),
            // SSE
            "sse_connect" => Some(OperationType::SseConnect),
            "sse_read_event" => Some(OperationType::SseReadEvent),
            "sse_close" => Some(OperationType::SseClose),
            // HTTP Server
            "http_server_start" => Some(OperationType::HttpServerStart),
            "http_server_receive" => Some(OperationType::HttpServerReceive),
            "http_server_respond" => Some(OperationType::HttpServerRespond),
            "http_server_stop" => Some(OperationType::HttpServerStop),
            "cert_generate" => Some(OperationType::CertGenerate),
            "cert_parse" => Some(OperationType::CertParse),
            "cert_info" => Some(OperationType::CertInfo),
            "cert_verify" => Some(OperationType::CertVerify),
            "key_generate" => Some(OperationType::KeyGenerate),
            "cert_self_signed" => Some(OperationType::CertSelfSigned),
            "path_join" => Some(OperationType::PathJoin),
            "path_basename" => Some(OperationType::PathBasename),
            "path_dirname" => Some(OperationType::PathDirname),
            "path_extension" => Some(OperationType::PathExtension),
            "path_stem" => Some(OperationType::PathStem),
            "path_is_absolute" => Some(OperationType::PathIsAbsolute),
            "path_normalize" => Some(OperationType::PathNormalize),
            "path_split" => Some(OperationType::PathSplit),
            "path_with_extension" => Some(OperationType::PathWithExtension),
            "path_parent" => Some(OperationType::PathParent),
            // YAML
            "yaml_parse" => Some(OperationType::YamlParse),
            "yaml_stringify" => Some(OperationType::YamlStringify),
            "yaml_validate" => Some(OperationType::YamlValidate),
            "yaml_to_json" => Some(OperationType::YamlToJson),
            "yaml_from_json" => Some(OperationType::YamlFromJson),
            "yaml_merge" => Some(OperationType::YamlMerge),
            "xml_parse" => Some(OperationType::XmlParse),
            "xml_stringify" => Some(OperationType::XmlStringify),
            // CSV
            "csv_parse" => Some(OperationType::CsvParse),
            "csv_stringify" => Some(OperationType::CsvStringify),
            "csv_headers" => Some(OperationType::CsvHeaders),
            "csv_parse_rows" => Some(OperationType::CsvParseRows),
            // TOML
            "toml_parse" => Some(OperationType::TomlParse),
            "toml_stringify" => Some(OperationType::TomlStringify),
            // Regex Extended
            "regex_split" => Some(OperationType::RegexSplit),
            "regex_escape" => Some(OperationType::RegexEscape),
            "regex_test" => Some(OperationType::RegexTest),
            "regex_captures" => Some(OperationType::RegexCaptures),
            "regex_find_all" => Some(OperationType::RegexFindAll),
            // UUID
            "uuid_v4" => Some(OperationType::UuidV4),
            "uuid_parse" => Some(OperationType::UuidParse),
            "uuid_is_valid" => Some(OperationType::UuidIsValid),
            "uuid_nil" => Some(OperationType::UuidNil),
            // Crypto Extended
            "hash_sha512" => Some(OperationType::HashSha512),
            "hmac_sha256" => Some(OperationType::HmacSha256),
            "hash_crc32" => Some(OperationType::HashCrc32),
            "constant_time_eq" => Some(OperationType::ConstantTimeEq),
            "compress_zstd" => Some(OperationType::CompressZstd),
            "decompress_zstd" => Some(OperationType::DecompressZstd),
            "compress_lz4" => Some(OperationType::CompressLz4),
            "decompress_lz4" => Some(OperationType::DecompressLz4),
            "compress_gzip" => Some(OperationType::CompressGzip),
            "decompress_gzip" => Some(OperationType::DecompressGzip),
            "fmt_number" => Some(OperationType::FmtNumber),
            "fmt_bytes" => Some(OperationType::FmtBytes),
            "fmt_duration" => Some(OperationType::FmtDuration),
            "fmt_hex" => Some(OperationType::FmtHex),
            "fmt_binary" => Some(OperationType::FmtBinary),
            "fmt_percent" => Some(OperationType::FmtPercent),
            // Convert Extended
            "parse_int" => Some(OperationType::ParseInt),
            "parse_float" => Some(OperationType::ParseFloat),
            // Time Extended
            "duration" => Some(OperationType::Duration),
            "elapsed" => Some(OperationType::Elapsed),
            "time_sleep" => Some(OperationType::TimeSleep),
            "add_duration" => Some(OperationType::AddDuration),
            "sub_duration" => Some(OperationType::SubDuration),
            "time_diff" => Some(OperationType::TimeDiff),
            "start_of" => Some(OperationType::StartOf),
            "end_of" => Some(OperationType::EndOf),
            "stats_mean" => Some(OperationType::StatsMean),
            "stats_median" => Some(OperationType::StatsMedian),
            "stats_mode" => Some(OperationType::StatsMode),
            "stats_variance" => Some(OperationType::StatsVariance),
            "stats_std_dev" => Some(OperationType::StatsStdDev),
            "stats_min_by" => Some(OperationType::StatsMinBy),
            "stats_max_by" => Some(OperationType::StatsMaxBy),
            "stats_sum" => Some(OperationType::StatsSum),
            "stats_percentile" => Some(OperationType::StatsPercentile),
            "stats_quantile" => Some(OperationType::StatsQuantile),
            "stats_covariance" => Some(OperationType::StatsCovariance),
            "stats_correlation" => Some(OperationType::StatsCorrelation),
            "text_wrap" => Some(OperationType::TextWrap),
            "text_dedent" => Some(OperationType::TextDedent),
            "text_indent" => Some(OperationType::TextIndent),
            "text_pad_left" => Some(OperationType::TextPadLeft),
            "text_pad_right" => Some(OperationType::TextPadRight),
            "text_truncate" => Some(OperationType::TextTruncate),
            "text_slug" => Some(OperationType::TextSlug),
            "text_camel_case" => Some(OperationType::TextCamelCase),
            "text_snake_case" => Some(OperationType::TextSnakeCase),
            "text_title_case" => Some(OperationType::TextTitleCase),
            // Encode Extended
            "html_escape" => Some(OperationType::HtmlEscape),
            "html_unescape" => Some(OperationType::HtmlUnescape),
            "base32_encode" => Some(OperationType::Base32Encode),
            "base32_decode" => Some(OperationType::Base32Decode),
            "reflect_type_of" => Some(OperationType::ReflectTypeOf),
            "reflect_type_name" => Some(OperationType::ReflectTypeName),
            "reflect_is_type" => Some(OperationType::ReflectIsType),
            "reflect_fields" => Some(OperationType::ReflectFields),
            "reflect_has_field" => Some(OperationType::ReflectHasField),
            "reflect_callable" => Some(OperationType::ReflectCallable),
            "reflect_arity" => Some(OperationType::ReflectArity),
            "reflect_inspect" => Some(OperationType::ReflectInspect),
            "set_from" => Some(OperationType::SetFrom),
            "set_union" => Some(OperationType::SetUnion),
            "set_intersection" => Some(OperationType::SetIntersection),
            "set_difference" => Some(OperationType::SetDifference),
            "set_symmetric_difference" => Some(OperationType::SetSymmetricDifference),
            "counter" => Some(OperationType::Counter),
            "most_common" => Some(OperationType::MostCommon),
            "ordered_map" => Some(OperationType::OrderedMap),
            "sort_asc" => Some(OperationType::SortAsc),
            "sort_desc" => Some(OperationType::SortDesc),
            "sort_by" => Some(OperationType::SortBy),
            "sort_by_key" => Some(OperationType::SortByKey),
            "stable_sort" => Some(OperationType::StableSort),
            "is_sorted" => Some(OperationType::IsSorted),
            "binary_search" => Some(OperationType::BinarySearch),
            "sort_reverse" => Some(OperationType::SortReverse),
            "exec" => Some(OperationType::Exec),
            "exec_status" => Some(OperationType::ExecStatus),
            "exec_output" => Some(OperationType::ExecOutput),
            "mutex_new" => Some(OperationType::MutexNew),
            "mutex_lock" => Some(OperationType::MutexLock),
            "mutex_unlock" => Some(OperationType::MutexUnlock),
            "waitgroup_new" => Some(OperationType::WaitgroupNew),
            "waitgroup_done" => Some(OperationType::WaitgroupDone),
            "waitgroup_wait" => Some(OperationType::WaitgroupWait),
            "await_all" => Some(OperationType::AwaitAll),
            "log_info" => Some(OperationType::LogInfo),
            "log_warn" => Some(OperationType::LogWarn),
            "log_error" => Some(OperationType::LogError),
            "log_debug" => Some(OperationType::LogDebug),
            "iter_chain" => Some(OperationType::IterChain),
            "iter_cycle" => Some(OperationType::IterCycle),
            "iter_repeat" => Some(OperationType::IterRepeat),
            "iter_product" => Some(OperationType::IterProduct),
            "iter_pairwise" => Some(OperationType::IterPairwise),
            "template_render" => Some(OperationType::TemplateRender),
            "flag_parse" => Some(OperationType::FlagParse),
            "flag_args" => Some(OperationType::FlagArgs),
            "gamma" => Some(OperationType::MathGamma),
            "lgamma" => Some(OperationType::MathLgamma),
            "erf" => Some(OperationType::MathErf),
            "erfc" => Some(OperationType::MathErfc),
            "expm1" => Some(OperationType::MathExpm1),
            "nextafter" => Some(OperationType::MathNextafter),
            "signbit" => Some(OperationType::MathSignbit),
            "chown" => Some(OperationType::FsChown),
            "hardlink" => Some(OperationType::FsHardlink),
            "pipe" => Some(OperationType::OsPipe),
            "format_float" => Some(OperationType::FormatFloat),
            "parse_uint" => Some(OperationType::ParseUint),
            "cli_fix" => Some(OperationType::CliFix),
            "cli_clean" => Some(OperationType::CliClean),
            "cli_tree" => Some(OperationType::CliTree),
            // Platform — Terminal
            "raw_mode_enable" => Some(OperationType::RawModeEnable),
            "raw_mode_disable" => Some(OperationType::RawModeDisable),
            "read_byte" => Some(OperationType::ReadByte),
            "read_byte_timeout" => Some(OperationType::ReadByteTimeout),
            // Platform — SDL2
            "sdl_init" => Some(OperationType::SdlInit),
            "sdl_set_color" => Some(OperationType::SdlSetColor),
            "sdl_clear" => Some(OperationType::SdlClear),
            "sdl_present" => Some(OperationType::SdlPresent),
            "sdl_draw_pixel" => Some(OperationType::SdlDrawPixel),
            "sdl_draw_line" => Some(OperationType::SdlDrawLine),
            "sdl_fill_rect" => Some(OperationType::SdlFillRect),
            "sdl_poll_event" => Some(OperationType::SdlPollEvent),
            "sdl_delay" => Some(OperationType::SdlDelay),
            "sdl_ticks" => Some(OperationType::SdlTicks),
            "sdl_destroy" => Some(OperationType::SdlDestroy),
            // Platform — Audio
            "audio_stream_new" => Some(OperationType::AudioStreamNew),
            "audio_write_samples" => Some(OperationType::AudioWriteSamples),
            "audio_drain" => Some(OperationType::AudioDrain),
            "audio_close" => Some(OperationType::AudioClose),
            // Platform — WebGPU
            "gpu_init" => Some(OperationType::GpuInit),
            "gpu_create_buffer" => Some(OperationType::GpuCreateBuffer),
            "gpu_create_shader" => Some(OperationType::GpuCreateShader),
            "gpu_create_pipeline" => Some(OperationType::GpuCreatePipeline),
            "gpu_begin_render_pass" => Some(OperationType::GpuBeginRenderPass),
            "gpu_draw" => Some(OperationType::GpuDraw),
            "gpu_end_render_pass" => Some(OperationType::GpuEndRenderPass),
            "gpu_submit" => Some(OperationType::GpuSubmit),
            "gpu_present" => Some(OperationType::GpuPresent),
            "gpu_write_buffer" => Some(OperationType::GpuWriteBuffer),
            "gpu_create_texture" => Some(OperationType::GpuCreateTexture),
            "gpu_destroy" => Some(OperationType::GpuDestroy),
            _ => None,
        }
    }

    /// All known operation types.
    pub const ALL: &'static [OperationType] = &[
        OperationType::Add,
        OperationType::Subtract,
        OperationType::Multiply,
        OperationType::Divide,
        OperationType::Modulo,
        OperationType::Power,
        OperationType::Sqrt,
        OperationType::Cbrt,
        OperationType::Hypot,
        OperationType::Negate,
        OperationType::Abs,
        OperationType::Min,
        OperationType::Max,
        OperationType::Round,
        OperationType::Floor,
        OperationType::Ceil,
        OperationType::Equal,
        OperationType::NotEqual,
        OperationType::Greater,
        OperationType::Less,
        OperationType::GreaterEq,
        OperationType::LessEq,
        OperationType::And,
        OperationType::Or,
        OperationType::Not,
        OperationType::Xor,
        OperationType::BitAnd,
        OperationType::BitOr,
        OperationType::BitXor,
        OperationType::BitNot,
        OperationType::BitShiftLeft,
        OperationType::BitShiftRight,
        OperationType::IfElse,
        OperationType::Switch,
        OperationType::Coalesce,
        OperationType::TryCatch,
        OperationType::Error,
        OperationType::FunctionDef,
        OperationType::FunctionCall,
        OperationType::AsyncSpawn,
        OperationType::AsyncAwait,
        OperationType::LoopGroup,
        OperationType::Concat,
        OperationType::Split,
        OperationType::Substring,
        OperationType::Length,
        OperationType::Replace,
        OperationType::ToUpper,
        OperationType::ToLower,
        OperationType::Trim,
        OperationType::TrimStart,
        OperationType::TrimEnd,
        OperationType::Contains,
        OperationType::StartsWith,
        OperationType::EndsWith,
        OperationType::CharAt,
        OperationType::IndexOf,
        OperationType::PadStart,
        OperationType::PadEnd,
        OperationType::RegexMatch,
        OperationType::StringJoin,
        OperationType::StringTemplate,
        OperationType::ToString,
        OperationType::ToInt64,
        OperationType::ToFloat64,
        OperationType::ToBool,
        OperationType::ToBytes,
        OperationType::FromBytes,
        OperationType::ParseJson,
        OperationType::ToJson,
        OperationType::ArrayGet,
        OperationType::ArraySet,
        OperationType::ArrayPush,
        OperationType::ArrayPop,
        OperationType::ArrayShift,
        OperationType::ArrayInsert,
        OperationType::ArrayRemove,
        OperationType::ArrayLength,
        OperationType::ArraySlice,
        OperationType::ArrayConcat,
        OperationType::ArrayContains,
        OperationType::ArrayReverse,
        OperationType::ArrayFlatten,
        OperationType::ArraySort,
        OperationType::ArrayJoin,
        OperationType::ArrayFilterNulls,
        OperationType::ArrayFromMap,
        OperationType::MapGet,
        OperationType::MapSet,
        OperationType::MapDelete,
        OperationType::MapHas,
        OperationType::MapKeys,
        OperationType::MapValues,
        OperationType::MapEntries,
        OperationType::MapMerge,
        OperationType::MapFromEntries,
        OperationType::MapSize,
        OperationType::BytesLength,
        OperationType::BytesSlice,
        OperationType::BytesConcat,
        OperationType::BytesContains,
        OperationType::Base64Encode,
        OperationType::Base64Decode,
        OperationType::BytesCompare,
        OperationType::BytesEqual,
        OperationType::BytesHasPrefix,
        OperationType::BytesHasSuffix,
        OperationType::BytesIndex,
        OperationType::BytesJoin,
        OperationType::BytesRepeat,
        OperationType::BytesSplit,
        OperationType::BytesTrim,
        OperationType::BytesFromString,
        OperationType::BytesToString,
        OperationType::ErrorNew,
        OperationType::ErrorWrap,
        OperationType::ErrorUnwrap,
        OperationType::ErrorIs,
        OperationType::ErrorChain,
        OperationType::Range,
        OperationType::Reduce,
        // JSON (6)
        OperationType::JsonGet,
        OperationType::JsonSet,
        OperationType::JsonDelete,
        OperationType::JsonFlatten,
        OperationType::JsonMerge,
        OperationType::JsonType,
        OperationType::JsonValidate,
        OperationType::JsonPrettyPrint,
        OperationType::JsonCompact,
        OperationType::JsonQuery,
        // DateTime (6)
        OperationType::NowTimestamp,
        OperationType::FormatTimestamp,
        OperationType::ParseTimestamp,
        OperationType::TimestampAdd,
        OperationType::TimestampDiff,
        OperationType::Sleep,
        // Hash/Encode (8)
        OperationType::HashSha256,
        OperationType::HashSha1,
        OperationType::HashBlake3,
        OperationType::HashMd5,
        OperationType::UrlEncode,
        OperationType::UrlDecode,
        OperationType::HexEncode,
        OperationType::HexDecode,
        // String extended (8)
        OperationType::StringReverse,
        OperationType::StringRepeat,
        OperationType::StringLines,
        OperationType::StringWords,
        OperationType::RegexReplace,
        OperationType::RegexExtract,
        OperationType::StringCount,
        OperationType::StringFormat,
        // Control Flow extended (2)
        OperationType::Assert,
        OperationType::DebugLog,
        // Type Conversion extended (2)
        OperationType::Typeof,
        OperationType::Default,
        // Array Higher-Order (20)
        OperationType::ArrayMap,
        OperationType::ArrayFilter,
        OperationType::ArrayFlatMap,
        OperationType::ArrayFind,
        OperationType::ArrayFindIndex,
        OperationType::ArrayEvery,
        OperationType::ArraySome,
        OperationType::ArrayZip,
        OperationType::ArrayEnumerate,
        OperationType::ArrayScan,
        OperationType::ArrayTake,
        OperationType::ArraySkip,
        OperationType::ArrayTakeWhile,
        OperationType::ArraySkipWhile,
        OperationType::ArrayGroupBy,
        OperationType::ArraySortBy,
        OperationType::ArrayUnique,
        OperationType::ArrayChunk,
        OperationType::ArrayWindow,
        OperationType::ArrayPartition,
        // Map Higher-Order (3)
        OperationType::MapMapValues,
        OperationType::MapFilterEntries,
        OperationType::MapUpdate,
        // String (1)
        OperationType::StringChars,
        // Math Aggregate (6)
        OperationType::MathSum,
        OperationType::MathProduct,
        OperationType::MathAverage,
        OperationType::MathMinOf,
        OperationType::MathMaxOf,
        OperationType::MathCount,
        // Type Checking (7)
        OperationType::IsNull,
        OperationType::IsString,
        OperationType::IsNumber,
        OperationType::IsArray,
        OperationType::IsMap,
        OperationType::IsBool,
        OperationType::IsBytes,
        // Math Extended (27)
        OperationType::Sin,
        OperationType::Cos,
        OperationType::Tan,
        OperationType::Asin,
        OperationType::Acos,
        OperationType::Atan,
        OperationType::Atan2,
        OperationType::Sinh,
        OperationType::Cosh,
        OperationType::Tanh,
        OperationType::Log,
        OperationType::Ln,
        OperationType::Log2,
        OperationType::Log10,
        OperationType::Exp,
        OperationType::ToRadians,
        OperationType::ToDegrees,
        OperationType::Clamp,
        OperationType::Lerp,
        OperationType::Sign,
        OperationType::Gcd,
        OperationType::Lcm,
        OperationType::IsNan,
        OperationType::IsInfinite,
        OperationType::IsFinite,
        OperationType::ApproxEq,
        OperationType::Remap,
        // Random (10)
        OperationType::RandomInt,
        OperationType::RandomFloat,
        OperationType::RandomBool,
        OperationType::RandomBytes,
        OperationType::RandomRange,
        OperationType::RandomChoice,
        OperationType::RandomShuffle,
        OperationType::RandomSample,
        OperationType::RandomUuid,
        OperationType::RandomString,
        // Filesystem (15)
        OperationType::FsRead,
        OperationType::FsWrite,
        OperationType::FsAppend,
        OperationType::FsExists,
        OperationType::FsRemove,
        OperationType::FsList,
        OperationType::FsMkdir,
        OperationType::FsCopy,
        OperationType::FsMove,
        OperationType::FsSize,
        OperationType::FsIsFile,
        OperationType::FsIsDir,
        OperationType::FsChmod,
        OperationType::FsSymlink,
        OperationType::FsReadlink,
        // Environment (7)
        OperationType::EnvGet,
        OperationType::EnvHas,
        OperationType::EnvKeys,
        OperationType::OsName,
        OperationType::OsArch,
        OperationType::ProcessPid,
        OperationType::CurrentDir,
        // Network (7)
        OperationType::HttpGet,
        OperationType::HttpPost,
        OperationType::HttpPut,
        OperationType::HttpDelete,
        OperationType::HttpRequest,
        OperationType::HttpHead,
        OperationType::HttpOptions,
        OperationType::HttpPatch,
        OperationType::UrlParse,
        OperationType::UrlJoin,
        // TCP (7)
        OperationType::TcpConnect,
        OperationType::TcpWrite,
        OperationType::TcpRead,
        OperationType::TcpClose,
        OperationType::TcpBind,
        OperationType::TcpAccept,
        OperationType::TcpServerClose,
        // UDP (4)
        OperationType::UdpBind,
        OperationType::UdpSendTo,
        OperationType::UdpRecvFrom,
        OperationType::UdpClose,
        // WebSocket (4)
        OperationType::WsConnect,
        OperationType::WsSend,
        OperationType::WsReceive,
        OperationType::WsClose,
        // SSE (3)
        OperationType::SseConnect,
        OperationType::SseReadEvent,
        OperationType::SseClose,
        // HTTP Server (4)
        OperationType::HttpServerStart,
        OperationType::HttpServerReceive,
        OperationType::HttpServerRespond,
        OperationType::HttpServerStop,
        // Certificate (6)
        OperationType::CertGenerate,
        OperationType::CertParse,
        OperationType::CertInfo,
        OperationType::CertVerify,
        OperationType::KeyGenerate,
        OperationType::CertSelfSigned,
        // Path (10)
        OperationType::PathJoin,
        OperationType::PathBasename,
        OperationType::PathDirname,
        OperationType::PathExtension,
        OperationType::PathStem,
        OperationType::PathIsAbsolute,
        OperationType::PathNormalize,
        OperationType::PathSplit,
        OperationType::PathWithExtension,
        OperationType::PathParent,
        // YAML (6)
        OperationType::YamlParse,
        OperationType::YamlStringify,
        OperationType::YamlValidate,
        OperationType::YamlToJson,
        OperationType::YamlFromJson,
        OperationType::YamlMerge,
        OperationType::XmlParse,
        OperationType::XmlStringify,
        // CSV (4)
        OperationType::CsvParse,
        OperationType::CsvStringify,
        OperationType::CsvHeaders,
        OperationType::CsvParseRows,
        // TOML (2)
        OperationType::TomlParse,
        OperationType::TomlStringify,
        // Regex Extended (5)
        OperationType::RegexSplit,
        OperationType::RegexEscape,
        OperationType::RegexTest,
        OperationType::RegexCaptures,
        OperationType::RegexFindAll,
        // UUID (4)
        OperationType::UuidV4,
        OperationType::UuidParse,
        OperationType::UuidIsValid,
        OperationType::UuidNil,
        // Crypto Extended (4)
        OperationType::HashSha512,
        OperationType::HmacSha256,
        OperationType::HashCrc32,
        OperationType::ConstantTimeEq,
        // Compress (6)
        OperationType::CompressZstd,
        OperationType::DecompressZstd,
        OperationType::CompressLz4,
        OperationType::DecompressLz4,
        OperationType::CompressGzip,
        OperationType::DecompressGzip,
        // Format (6)
        OperationType::FmtNumber,
        OperationType::FmtBytes,
        OperationType::FmtDuration,
        OperationType::FmtHex,
        OperationType::FmtBinary,
        OperationType::FmtPercent,
        // Convert Extended (2)
        OperationType::ParseInt,
        OperationType::ParseFloat,
        // Time Extended (8)
        OperationType::Duration,
        OperationType::Elapsed,
        OperationType::TimeSleep,
        OperationType::AddDuration,
        OperationType::SubDuration,
        OperationType::TimeDiff,
        OperationType::StartOf,
        OperationType::EndOf,
        // Stats (12)
        OperationType::StatsMean,
        OperationType::StatsMedian,
        OperationType::StatsMode,
        OperationType::StatsVariance,
        OperationType::StatsStdDev,
        OperationType::StatsMinBy,
        OperationType::StatsMaxBy,
        OperationType::StatsSum,
        OperationType::StatsPercentile,
        OperationType::StatsQuantile,
        OperationType::StatsCovariance,
        OperationType::StatsCorrelation,
        // Text (10)
        OperationType::TextWrap,
        OperationType::TextDedent,
        OperationType::TextIndent,
        OperationType::TextPadLeft,
        OperationType::TextPadRight,
        OperationType::TextTruncate,
        OperationType::TextSlug,
        OperationType::TextCamelCase,
        OperationType::TextSnakeCase,
        OperationType::TextTitleCase,
        // Encode Extended (4)
        OperationType::HtmlEscape,
        OperationType::HtmlUnescape,
        OperationType::Base32Encode,
        OperationType::Base32Decode,
        // Reflect (8)
        OperationType::ReflectTypeOf,
        OperationType::ReflectTypeName,
        OperationType::ReflectIsType,
        OperationType::ReflectFields,
        OperationType::ReflectHasField,
        OperationType::ReflectCallable,
        OperationType::ReflectArity,
        OperationType::ReflectInspect,
        // Collections (8)
        OperationType::SetFrom,
        OperationType::SetUnion,
        OperationType::SetIntersection,
        OperationType::SetDifference,
        OperationType::SetSymmetricDifference,
        OperationType::Counter,
        OperationType::MostCommon,
        OperationType::OrderedMap,
        // Sort (8)
        OperationType::SortAsc,
        OperationType::SortDesc,
        OperationType::SortBy,
        OperationType::SortByKey,
        OperationType::StableSort,
        OperationType::IsSorted,
        OperationType::BinarySearch,
        OperationType::SortReverse,
        // Subprocess (3)
        OperationType::Exec,
        OperationType::ExecStatus,
        OperationType::ExecOutput,
        // Sync (6)
        OperationType::MutexNew,
        OperationType::MutexLock,
        OperationType::MutexUnlock,
        OperationType::WaitgroupNew,
        OperationType::WaitgroupDone,
        OperationType::WaitgroupWait,
        // Concurrency (1)
        OperationType::AwaitAll,
        // Log (4)
        OperationType::LogInfo,
        OperationType::LogWarn,
        OperationType::LogError,
        OperationType::LogDebug,
        // Itertools (5)
        OperationType::IterChain,
        OperationType::IterCycle,
        OperationType::IterRepeat,
        OperationType::IterProduct,
        OperationType::IterPairwise,
        // Template (1)
        OperationType::TemplateRender,
        // Flag (2)
        OperationType::FlagParse,
        OperationType::FlagArgs,
        // Additional math (7)
        OperationType::MathGamma,
        OperationType::MathLgamma,
        OperationType::MathErf,
        OperationType::MathErfc,
        OperationType::MathExpm1,
        OperationType::MathNextafter,
        OperationType::MathSignbit,
        // Additional OS (3)
        OperationType::FsChown,
        OperationType::FsHardlink,
        OperationType::OsPipe,
        // Additional strconv (2)
        OperationType::FormatFloat,
        OperationType::ParseUint,
        // Additional CLI (3)
        OperationType::CliFix,
        OperationType::CliClean,
        OperationType::CliTree,
        // Platform — Terminal (4)
        OperationType::RawModeEnable,
        OperationType::RawModeDisable,
        OperationType::ReadByte,
        OperationType::ReadByteTimeout,
        // Platform — SDL2 (11)
        OperationType::SdlInit,
        OperationType::SdlSetColor,
        OperationType::SdlClear,
        OperationType::SdlPresent,
        OperationType::SdlDrawPixel,
        OperationType::SdlDrawLine,
        OperationType::SdlFillRect,
        OperationType::SdlPollEvent,
        OperationType::SdlDelay,
        OperationType::SdlTicks,
        OperationType::SdlDestroy,
        // Platform — Audio (4)
        OperationType::AudioStreamNew,
        OperationType::AudioWriteSamples,
        OperationType::AudioDrain,
        OperationType::AudioClose,
        // Platform — WebGPU (12)
        OperationType::GpuInit,
        OperationType::GpuCreateBuffer,
        OperationType::GpuCreateShader,
        OperationType::GpuCreatePipeline,
        OperationType::GpuBeginRenderPass,
        OperationType::GpuDraw,
        OperationType::GpuEndRenderPass,
        OperationType::GpuSubmit,
        OperationType::GpuPresent,
        OperationType::GpuWriteBuffer,
        OperationType::GpuCreateTexture,
        OperationType::GpuDestroy,
    ];
}

impl std::fmt::Display for OperationType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_operation_type_all_count() {
        assert_eq!(OperationType::ALL.len(), 468);
    }

    #[test]
    fn test_operation_type_roundtrip() {
        for op in OperationType::ALL {
            let s = op.as_str();
            let parsed = OperationType::parse(s).unwrap();
            assert_eq!(*op, parsed);
            assert_eq!(op.to_string(), s);
        }
    }

    #[test]
    fn test_operation_type_parse_unknown() {
        assert!(OperationType::parse("unknown_op").is_none());
    }

    #[test]
    fn test_operation_type_unique_ids() {
        let mut seen = std::collections::HashSet::new();
        for op in OperationType::ALL {
            assert!(seen.insert(op.as_str()), "duplicate: {}", op.as_str());
        }
    }

}
